version: '3.8'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    networks:
      hassiospnetwork:
        ipv4_address: 172.20.0.2

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
      - "8083:8083"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=hassiosp
      - DOCKER_INFLUXDB_INIT_PASSWORD=hassiosp
      - DOCKER_INFLUXDB_INIT_ORG=hassiosp
      - DOCKER_INFLUXDB_INIT_BUCKET=hassiosp
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=hassiosp
    networks:
      hassiospnetwork:
        ipv4_address: 172.20.0.3

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana # NOTE: must run "chown -R 472:472 ./data/grafana"
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    networks:
      hassiospnetwork:
        ipv4_address: 172.20.0.4

networks:
  hassiospnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
