#!/bin/bash

ip=$(ifconfig |
        grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*'  |
        grep -Eo '([0-9]*\.){3}[0-9]*'  |
        grep -v '127.0.0.1'  |
        grep ^192)

echo Setting ip from localhost to $ip

sed -i "s/localhost/$ip/g" data/homeassistant/config/configuration.yaml 